default: cpsc2150/myDeque/ArrayDeque.java cpsc2150/myDeque/ListDeque.java cpsc2150/myDeque/IDeque.java cpsc2150/myDeque/DequeApp.java
	javac cpsc2150/myDeque/ArrayDeque.java cpsc2150/myDeque/ListDeque.java cpsc2150/myDeque/IDeque.java cpsc2150/myDeque/DequeApp.java

run: cpsc2150/myDeque/ArrayDeque.class cpsc2150/myDeque/ListDeque.class cpsc2150/myDeque/IDeque.class cpsc2150/myDeque/DequeApp.class
	java cpsc2150.myDeque.DequeApp

clean:
	rm -f cpsc2150/myDeque/*.class
