default: cpsc2150/MyDeque/ArrayDeque.java cpsc2150/MyDeque/AbsDeque.java cpsc2150/MyDeque/ListDeque.java cpsc2150/MyDeque/IDeque.java cpsc2150/MyDeque/DequeApp.java
	javac cpsc2150/MyDeque/ArrayDeque.java cpsc2150/MyDeque/AbsDeque.java cpsc2150/MyDeque/ListDeque.java cpsc2150/MyDeque/IDeque.java cpsc2150/MyDeque/DequeApp.java

run: cpsc2150/MyDeque/ArrayDeque.class cpsc2150/MyDeque/AbsDeque.java cpsc2150/MyDeque/ListDeque.class cpsc2150/MyDeque/IDeque.class cpsc2150/MyDeque/DequeApp.class
	java cpsc2150.MyDeque.DequeApp

clean:
	rm -f cpsc2150/MyDeque/*.class
