default: cpsc2150/extendedConnectX/*.java
	javac -Xlint cpsc2150/extendedConnectX/*.java

run: cpsc2150/extendedConnectX/*.class
	java cpsc2150.extendedConnectX.GameScreen

clean:
	rm -f cpsc2150/extendedConnectX/*.class
